### ISSUE TITLE
Documentation, Implementation and Workflow::next() throws Exception\MoreThanOneOpenTransitionException

### ISSUE THREAD

**Issue by dotZoki** [alterway/component-workflow#4]
I might be wrong but looking the documentation and the implementation it seems that it is not possible to do `$workflow->initialize('article.published')->next($context)` call when article is older than 1 month. 
next() will throw `Exception\MoreThanOneOpenTransitionException` because `ArchivableArticleSpecification` and `DeletableArticleSpecification` return true. 

Even if you catch the exception how do you decide and/or force certain transition in this case?

**Comment by trompette** [comment]
Hi @dotZoki,

The purpose of this component is to abstract away life cycles from entities. You define a deterministic life cycle and you let the component manage the status of your entity.

That means you do not decide and/or force transition. A transition is open or not given a context:
- when open, the component will dispatch an event to let you listen to it to implement any behavior
- when closed, the component will throw an exception to let you know that the life cycle is stuck

You are right regarding the `$workflow->initialize('article.published')->next($context)`. This is because the context is too generic and makes both specifications true.

I will change the documentation.

**Comment by trompette** [comment]
@dotZoki, could you please review #5? Thanks!

**Comment by dotZoki** [comment]
Hi,

Seems OK.
